---
- debug:
    msg: "System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}"

- shell: /bin/date
  register: result

- debug:
    var: result

- name: simpel module
  hello: name=philipp

#- which:
#    name: "python2"
#    dest: "python"


- name: long running
  shell: "sleep 300"
