---
- debug:
    msg: "System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}"

- debug:
    msg: "firewall_cservices {{ firewall_cservices }}"

- debug:
    msg: "firewall_cservices {{ semodule_configs }}"

- shell: /bin/date
  register: result

- debug:
    var: result
  when: ansible_local | hasLocalFactVersion('tomcat_ms','10.0')

- name: simpel module
  hello: name=philipp

- name: wrong variable
  ping: data={{ wrong_var }}

- name: long running
  shell: "sleep 300"
